/**
 * Utility helper to auto-generate and validate BHYT (Health Insurance Card) numbers based on CCCD (National ID).
 */

export interface BhytOptions {
  isStudent?: boolean;
  studentType?: string;
  occupation?: string;
  isPoor?: boolean;
}

/**
 * Tự động tạo/cập nhật Mã số thẻ BHYT (15 ký tự chuẩn Việt Nam) dựa trên Số CCCD/Định danh cá nhân.
 * Ví dụ: CCCD "070200012345" -> Mã BHYT "GD4700200012345"
 */
export function generateBhytFromCccd(cccd: string, options?: BhytOptions): string {
  if (!cccd) return "";
  const cleanCccd = cccd.trim().replace(/\D/g, "");
  if (cleanCccd.length < 4) return "";

  let prefix = "GD";
  if (options?.isStudent) {
    prefix = options.studentType === "Sinh viên" ? "SV" : "HS";
  } else if (options?.occupation) {
    const occ = options.occupation.toLowerCase();
    if (occ.includes("sinh viên") || occ.includes("học sinh") || occ.includes("mầm non")) {
      prefix = "HS";
    } else if (occ.includes("doanh nghiệp") || occ.includes("công nhân") || occ.includes("nhân viên") || occ.includes("thợ")) {
      prefix = "DN";
    } else if (occ.includes("công chức") || occ.includes("viên chức") || occ.includes("bác sĩ") || occ.includes("giáo viên") || occ.includes("cán bộ")) {
      prefix = "HC";
    } else if (occ.includes("hưu trí") || occ.includes("nghỉ hưu")) {
      prefix = "HT";
    }
  }

  const benefitTier = options?.isPoor ? "3" : "4";
  const provinceCode = "70"; // Mã tỉnh Tây Ninh (Ninh Phú)

  // 10 số BHXH/BHYT định danh rút từ 10 số cuối của CCCD
  const bhxh10Digits = cleanCccd.slice(-10).padStart(10, "0");

  return `${prefix}${benefitTier}${provinceCode}${bhxh10Digits}`;
}

export function isAutoGeneratedBhyt(insuranceId?: string): boolean {
  if (!insuranceId || !insuranceId.trim()) return true;
  const trimmed = insuranceId.trim().toUpperCase();
  return /^(GD|HS|SV|DN|HC|HT|CN|CB)[345][0-9]{12}$/.test(trimmed) || /^(GD|HS|SV|DN|HC|HT|CN|CB)[0-9]{10,12}$/.test(trimmed);
}
